In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)

In [4]:
df = pd.read_csv(r"C:\Users\hp\Documents\Projects\food_delivery_analytics\data\raw\Rider-Info.csv")

In [5]:
df.head()

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
0,2021-01-26 02:21:35,556753,2021-01-26 00:00:00,2021-01-26 02:21:59,2021-01-26 02:22:08,2021-01-26 02:32:51,2021-01-26 02:49:47,11696,1.5666,2.65,46.0,46.0,0,0.0,621.0,NaN,NaN,NaN,NaN,NaN
1,2021-01-26 02:33:16,556754,2021-01-26 00:00:00,2021-01-26 02:33:57,2021-01-26 02:34:45,2021-01-26 02:50:25,2021-01-26 03:11:15,18117,2.5207,2.76,8.0,8.0,0,0.0,105.0,NaN,NaN,NaN,3.266667,NaN
2,2021-01-26 02:39:49,556755,2021-01-26 00:00:00,2021-01-26 02:39:57,2021-01-26 02:40:13,2021-01-26 02:56:00,2021-01-26 03:12:46,18623,2.2074,4.80,1.0,1.0,0,0.0,66.0,NaN,NaN,NaN,9.816667,NaN
3,2021-01-26 02:47:53,556756,2021-01-26 00:00:00,2021-01-26 02:48:25,2021-01-26 02:49:06,2021-01-26 03:21:51,2021-01-26 03:41:05,15945,2.1894,6.38,1.0,1.0,0,0.0,127.0,NaN,NaN,NaN,17.533333,NaN
4,2021-01-26 03:06:30,556757,2021-01-26 00:00:00,2021-01-26 03:07:21,2021-01-26 03:07:57,2021-01-26 03:31:38,2021-01-26 04:00:15,17589,2.7870,4.01,34.0,34.0,0,0.0,84.0,NaN,NaN,NaN,1.350000,NaN

In [6]:
df.tail()

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
449995,2021-02-06 10:03:16,130226,2021-02-06 00:00:00,2021-02-06 10:03:44,2021-02-06 10:04:14,2021-02-06 10:27:29,2021-02-06 10:44:08,1006,0.5789,0.19,4.0,4.0,0,0.0,127.0,NaN,NaN,NaN,369.516667,NaN
449996,2021-02-06 10:03:17,130227,2021-02-06 00:00:00,2021-02-06 10:03:18,2021-02-06 10:04:34,2021-02-06 10:22:17,2021-02-06 10:31:43,279,1.9863,1.19,81.0,81.0,0,0.0,105.0,NaN,NaN,NaN,239.133333,NaN
449997,2021-02-06 10:03:18,130228,2021-02-06 00:00:00,2021-02-06 10:04:06,2021-02-06 10:04:39,2021-02-06 10:19:06,2021-02-06 10:26:56,3161,1.5944,1.61,28.0,28.0,0,0.0,1488.0,NaN,NaN,NaN,204.150000,NaN
449998,2021-02-06 10:03:19,130229,2021-02-06 00:00:00,2021-02-06 10:03:19,2021-02-06 10:05:41,2021-02-06 10:20:39,2021-02-06 10:30:41,9396,2.8939,4.68,72.0,72.0,0,0.0,105.0,NaN,NaN,NaN,65.583333,NaN
449999,2021-02-06 10:03:24,130230,2021-02-06 00:00:00,2021-02-06 10:03:45,2021-02-06 10:05:14,2021-02-06 10:13:26,2021-02-06 10:19:41,2078,1.8925,0.09,30.0,30.0,0,0.0,108.0,NaN,NaN,NaN,212.000000,NaN

In [7]:
df.columns

Index(['order_time', 'order_id', 'order_date', 'allot_time', 'accept_time',
       'pickup_time', 'delivered_time', 'rider_id', 'first_mile_distance',
       'last_mile_distance', 'alloted_orders', 'delivered_orders', 'cancelled',
       'undelivered_orders', 'lifetime_order_count', 'reassignment_method',
       'reassignment_reason', 'reassigned_order', 'session_time',
       'cancelled_time'],
      dtype='object')

In [8]:
df.dtypes

order_time               object
order_id                  int64
order_date               object
allot_time               object
accept_time              object
pickup_time              object
delivered_time           object
rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
cancelled                 int64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method      object
reassignment_reason      object
reassigned_order        float64
session_time            float64
cancelled_time           object
dtype: object

In [9]:
df['cancelled_time'].unique()

array([nan, '2021-01-26 04:51:46', '2021-01-26 04:08:50', ...,
       '2021-02-06 10:45:49', '2021-02-06 10:04:41',
       '2021-02-06 10:15:38'], shape=(5177,), dtype=object)

In [10]:
df['session_time'].unique()

array([         nan,   3.26666667,   9.81666667, ..., 381.28333333,
       220.03333333, 278.75      ], shape=(65873,))

In [11]:
df.sample()

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
179070,2021-01-30 14:13:13,418134,2021-01-30 00:00:00,2021-01-30 14:15:23,2021-01-30 14:15:31,2021-01-30 14:40:01,2021-01-30 15:18:51,14522,0.7872,4.76,84.0,84.0,0,0.0,314.0,NaN,NaN,NaN,23.166667,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450000 entries, 0 to 449999
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_time            450000 non-null  object
 1   order_id              450000 non-null  int64
 2   order_date            450000 non-null  object
 3   allot_time            450000 non-null  object
 4   accept_time           449843 non-null  object
 5   pickup_time           447579 non-null  object
 6   delivered_time        444782 non-null  object
 7   rider_id              450000 non-null  int64
 8   first_mile_distance   450000 non-null  float64
 9   last_mile_distance    450000 non-null  float64
 10  alloted_orders        433052 non-null  float64
 11  delivered_orders      432659 non-null  float64
 12  cancelled             450000 non-null  int64
 13  undelivered_orders    432659 non-null  float64
 14  lifetime_order_count  449947 non-null  float64
 15  reassignment_method   13744 non-null   object
 16  reassignment_reason   13753 non-null   object
 17  reassigned_order      13753 non-null   float64
 18  session_time          446325 non-null  float64
 19  cancelled_time        5218 non-null    object
dtypes: float64(8), int64(3), object(9)
memory usage: 68.7+ MB

In [13]:
df.isna().sum()

order_time                   0
order_id                     0
order_date                   0
allot_time                   0
accept_time                157
pickup_time               2421
delivered_time            5218
rider_id                     0
first_mile_distance          0
last_mile_distance           0
alloted_orders           16948
delivered_orders         17341
cancelled                    0
undelivered_orders       17341
lifetime_order_count        53
reassignment_method     436256
reassignment_reason     436247
reassigned_order        436247
session_time              3675
cancelled_time          444782
dtype: int64

In [17]:
df.shape[0]

450000

In [19]:
df.shape[0] - df['reassigned_order'].isna().sum()

np.int64(13753)

In [20]:
df.shape[0] - df['cancelled_time'].isna().sum()

np.int64(5218)

In [21]:
df['delivered_time'].isna().sum()

np.int64(5218)

In [23]:
df[df['cancelled'] == 1].shape[0]

5218

In [24]:
df[(df['delivered_time'].notna()) & (df['cancelled'] == 1)]

Empty DataFrame
Columns: [order_time, order_id, order_date, allot_time, accept_time, pickup_time, delivered_time, rider_id, first_mile_distance, last_mile_distance, alloted_orders, delivered_orders, cancelled, undelivered_orders, lifetime_order_count, reassignment_method, reassignment_reason, reassigned_order, session_time, cancelled_time]
Index: []

In [26]:
df[(df['delivered_time'].notna()) & (df['cancelled'] == 0)].shape[0]

444782

In [28]:
df[(df['delivered_time'].isna()) & (df['cancelled'] == 1)].shape[0]

5218

In [27]:
# It means whenever the delivered_time is not present there in the dataset the main reason is the ordered is cancelled

In [29]:
df['delivered_orders'].value_counts()

delivered_orders
6.0      3798
4.0      3698
5.0      3697
7.0      3645
3.0      3528
         ...
562.0      12
420.0      10
553.0       9
522.0       8
482.0       5
Name: count, Length: 504, dtype: int64

In [30]:
df['undelivered_orders'].value_counts()

undelivered_orders
0.0    232686
1.0    118103
2.0     50582
3.0     20011
4.0      7733
5.0      1851
6.0       932
7.0       600
8.0       105
9.0        56
Name: count, dtype: int64

In [ ]:
df[df['delivered_orders'].isna()].sample()

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
4955,2021-01-26 07:36:18,561708,2021-01-26 00:00:00,2021-01-26 07:37:16,2021-01-26 07:38:22,2021-01-26 07:57:44,2021-01-26 08:09:12,18755,1.6213,1.69,NaN,NaN,0,NaN,373.0,NaN,NaN,NaN,96.3,NaN

In [35]:
df[(df['delivered_orders'].isna()) & (df['rider_id'] == 18755)].head(10)

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
4955,2021-01-26 07:36:18,561708,2021-01-26 00:00:00,2021-01-26 07:37:16,2021-01-26 07:38:22,2021-01-26 07:57:44,2021-01-26 08:09:12,18755,1.621300,1.69,NaN,NaN,0,NaN,373.0,NaN,NaN,NaN,96.300000,NaN
18523,2021-01-26 14:12:15,575277,2021-01-26 00:00:00,2021-01-26 14:13:43,2021-01-26 14:14:42,2021-01-26 15:05:05,2021-01-26 15:21:14,18755,0.141778,1.20,NaN,NaN,0,NaN,373.0,NaN,NaN,NaN,250.316667,NaN
18611,2021-01-26 14:13:07,575364,2021-01-26 00:00:00,2021-01-26 14:13:43,2021-01-26 14:14:51,2021-01-26 14:24:41,2021-01-26 14:48:29,18755,0.060384,2.27,NaN,NaN,0,NaN,373.0,NaN,NaN,NaN,251.183333,NaN
23127,2021-01-26 15:01:30,579880,2021-01-26 00:00:00,2021-01-26 15:17:03,2021-01-26 15:17:20,2021-01-26 15:26:30,2021-01-26 17:13:43,18755,0.642300,1.83,NaN,NaN,0,NaN,373.0,auto,Auto Reassignment basis Inaction. coreengine.t...,1.0,299.566667,NaN
28494,2021-01-26 15:59:29,585248,2021-01-26 00:00:00,2021-01-26 16:03:04,2021-01-26 16:06:15,2021-01-26 16:13:31,2021-01-26 16:29:44,18755,0.579200,3.97,NaN,NaN,0,NaN,373.0,NaN,NaN,NaN,357.550000,NaN

In [36]:
df['reassignment_reason'].unique()

array([nan, 'Reassignment Request from SE portal.',
       'Auto Reassignment basis Inaction. coreengine.tasks.repush_order_to_aa_bucket',
       'Reassign'], dtype=object)

In [37]:
df[df['reassignment_reason'].notna()]

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
9,2021-01-26 03:15:18,556762,2021-01-26 00:00:00,2021-01-26 03:21:27,2021-01-26 03:22:04,2021-01-26 04:14:56,2021-01-26 04:38:39,21037,2.8786,2.61,NaN,NaN,0,NaN,1.0,auto,Reassignment Request from SE portal.,1.0,NaN,NaN
20,2021-01-26 03:28:13,556773,2021-01-26 00:00:00,2021-01-26 04:09:50,2021-01-26 04:11:06,NaN,NaN,12885,2.8438,6.81,29.0,29.0,1,0.0,449.0,auto,Reassignment Request from SE portal.,1.0,NaN,2021-01-26 04:51:46
38,2021-01-26 03:38:14,556791,2021-01-26 00:00:00,2021-01-26 03:54:07,2021-01-26 03:54:28,2021-01-26 04:09:45,2021-01-26 04:15:23,10869,1.5504,0.17,145.0,144.0,0,1.0,2037.0,auto,Auto Reassignment basis Inaction. coreengine.t...,1.0,56.683333,NaN
52,2021-01-26 03:42:17,556805,2021-01-26 00:00:00,2021-01-26 03:58:13,2021-01-26 03:59:35,2021-01-26 04:13:25,2021-01-26 04:44:06,313,2.9776,1.43,76.0,76.0,0,0.0,439.0,auto,Auto Reassignment basis Inaction. coreengine.t...,1.0,NaN,NaN
100,2021-01-26 03:54:11,556853,2021-01-26 00:00:00,2021-01-26 05:29:06,2021-01-26 05:30:01,NaN,NaN,2391,2.9217,5.20,118.0,114.0,1,4.0,860.0,auto,Reassignment Request from SE portal.,1.0,22.516667,2021-01-26 05:45:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449853,2021-02-06 09:54:59,130084,2021-02-06 00:00:00,2021-02-06 10:10:01,2021-02-06 10:11:29,2021-02-06 10:19:13,2021-02-06 10:29:18,11846,1.4333,2.64,32.0,32.0,0,0.0,98.0,auto,Auto Reassignment basis Inaction. coreengine.t...,1.0,84.350000,NaN
449880,2021-02-06 09:56:25,130111,2021-02-06 00:00:00,2021-02-06 10:11:27,2021-02-06 10:11:57,2021-02-06 10:20:12,2021-02-06 10:28:19,982,0.3585,0.35,228.0,227.0,0,1.0,568.0,auto,Auto Reassignment basis Inaction. coreengine.t...,1.0,266.416667,NaN
449934,2021-02-06 09:59:45,130165,2021-02-06 00:00:00,2021-02-06 10:13:48,2021-02-06 10:14:12,2021-02-06 10:21:27,2021-02-06 10:30:56,9797,0.8713,1.02,257.0,255.0,0,2.0,504.0,auto,Reassignment Request from SE portal.,1.0,194.033333,NaN
449942,2021-02-06 10:00:13,130173,2021-02-06 00:00:00,2021-02-06 10:19:28,2021-02-06 10:19:42,2021-02-06 10:27:45,2021-02-06 10:54:06,8861,2.4797,4.45,96.0,96.0,0,0.0,2998.0,auto,Auto Reassignment basis Inaction. coreengine.t...,1.0,260.966667,NaN
449951,2021-02-06 10:00:39,130182,2021-02-06 00:00:00,2021-02-06 10:18:32,2021-02-06 10:18:59,2021-02-06 10:38:18,2021-02-06 10:52:25,2382,0.5007,1.27,241.0,239.0,0,2.0,24022.0,auto,Reassignment Request from SE portal.,1.0,384.683333,NaN

In [ ]:
df[(df['alloted_orders'].isna()) & (df['delivered_orders'].isna())].shape[0]

16948

In [41]:
df[df['delivered_orders'].isna()].shape[0] - df[(df['alloted_orders'].isna()) & (df['delivered_orders'].isna())].shape[0]

393

In [43]:
df[(df['alloted_orders'].isna()) & (df['undelivered_orders'].isna())].shape[0]

16948

In [44]:
df[(df['alloted_orders'].notna()) & (df['delivered_orders'].isna())].shape[0]

393

In [46]:
df[(df['alloted_orders'].notna()) & (df['delivered_orders'].isna())].head()

,order_time,order_id,order_date,allot_time,accept_time,pickup_time,delivered_time,rider_id,first_mile_distance,last_mile_distance,alloted_orders,delivered_orders,cancelled,undelivered_orders,lifetime_order_count,reassignment_method,reassignment_reason,reassigned_order,session_time,cancelled_time
3976,2021-01-26 07:18:54,560729,2021-01-26 00:00:00,2021-01-26 07:19:46,2021-01-26 07:23:17,2021-01-26 07:42:29,NaN,21200,0.577300,1.87,2.0,NaN,1,NaN,285.0,NaN,NaN,NaN,17.916667,2021-01-26 08:16:21
4523,2021-01-26 07:30:21,561271,2021-01-26 00:00:00,2021-01-26 07:30:22,2021-01-26 07:30:33,2021-01-26 07:48:07,2021-01-26 07:53:15,20008,2.251600,3.34,1.0,NaN,0,NaN,1835.0,NaN,NaN,NaN,1.133333,NaN
6433,2021-01-26 08:03:21,563186,2021-01-26 00:00:00,2021-01-26 08:03:42,2021-01-26 08:04:23,NaN,NaN,21251,0.149636,0.42,1.0,NaN,1,NaN,58.0,NaN,NaN,NaN,3.350000,2021-01-26 08:42:43
6524,2021-01-26 08:05:23,563277,2021-01-26 00:00:00,2021-01-26 08:05:24,2021-01-26 08:05:53,2021-01-26 08:23:49,NaN,21252,1.152700,4.19,2.0,NaN,1,NaN,1.0,NaN,NaN,NaN,60.383333,2021-01-26 09:43:38
7372,2021-01-26 08:23:30,564125,2021-01-26 00:00:00,2021-01-26 08:24:06,2021-01-26 08:26:17,2021-01-26 08:40:38,2021-01-26 08:45:50,13157,0.023793,0.48,1.0,NaN,0,NaN,3.0,NaN,NaN,NaN,5.233333,NaN

In [47]:
df[(df['alloted_orders'].notna()) & (df['delivered_orders'].isna())]['order_time']

3976      2021-01-26 07:18:54
4523      2021-01-26 07:30:21
6433      2021-01-26 08:03:21
6524      2021-01-26 08:05:23
7372      2021-01-26 08:23:30
                 ...
441096    2021-02-06 07:10:40
444182    2021-02-06 08:01:56
445705    2021-02-06 08:28:06
447564    2021-02-06 08:56:42
449550    2021-02-06 09:40:29
Name: order_time, Length: 393, dtype: object